### ISSUE TITLE
IDEA 无法自动提示

### ISSUE THREAD

**Issue by gentlemm** [longyan/phpkafka#1]
安装：
composer require longlang/phpkafka

框架：
hyperf ~2.0

问题：
IDEA 无法自动提示

![image](https://user-images.githubusercontent.com/16871357/97401521-e9b25a00-192b-11eb-80f6-c71878dffaf6.png)

**Comment by sy-records** [comment]
检查包是否安装成功

![image](https://user-images.githubusercontent.com/33931153/97402260-3a768280-192d-11eb-8f1b-73bb2432f081.png)
![image](https://user-images.githubusercontent.com/33931153/97402283-44988100-192d-11eb-9aec-6c172ba3c2dd.png)
