### ISSUE TITLE
 [16] This is not the correct coordinator

### ISSUE THREAD

**Issue by a53abc** [longyan/phpkafka#2]
docker运行
PHP 7.2.29 , swoole 4.5.7
kafka 官方镜像: wurstmeister/kafka:2.12-2.5.0

使用代码为官方demo, produce成功，consumer失败。
Fatal error: Uncaught longlang\phpkafka\Exception\KafkaErrorException: [16] This is not the correct coordinator. in /var/www/html/vendor/longlang/phpkafka/src/Protocol/
ErrorCode.php:385
Stack trace:
#0 /var/www/html/vendor/longlang/phpkafka/src/Consumer/OffsetManager.php(78): longlang\phpkafka\Protocol\ErrorCode::check(16)
#1 /var/www/html/vendor/longlang/phpkafka/src/Consumer/Consumer.php(70): longlang\phpkafka\Consumer\OffsetManager->updateOffsets()
#2 /var/www/html/test/kafka/consumer.php(14): longlang\phpkafka\Consumer\Consumer->__construct(Object(longlang\phpkafka\Consumer\ConsumerConfig))
#3 {main}
  thrown in /var/www/html/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php on line 385

设置group信息后同样报错

**Comment by a53abc** [comment]
consumer代码
<?php

require dirname(dirname(__DIR__)).'/vendor/autoload.php';
use longlang\phpkafka\Consumer\ConsumeMessage;
use longlang\phpkafka\Consumer\Consumer;
use longlang\phpkafka\Consumer\ConsumerConfig;

$config = new ConsumerConfig();
$config->setBroker('kafka212:9092');
$config->setTopic('test');
//$config->setGroupId("test1");
//$config->setMemberId('hello');
//$config->setGroupInstanceId('1');
$consumer = new Consumer($config);
while(true)
{
    $message = $consumer->consume();
    if($message)
    {
        var_dump($message->getKey() . ':' . $message->getValue());
        $consumer->ack($message->getPartition()); // 手动提交
    }
    sleep(1);
}

**Comment by a53abc** [comment]
`<?php

require dirname(dirname(__DIR__)).'/vendor/autoload.php';
use longlang\phpkafka\Consumer\ConsumeMessage;
use longlang\phpkafka\Consumer\Consumer;
use longlang\phpkafka\Consumer\ConsumerConfig;

$config = new ConsumerConfig();
$config->setBroker('kafka212:9092');
$config->setTopic('test');
//$config->setGroupId("test1");
//$config->setMemberId('hello');
//$config->setGroupInstanceId('1');
$consumer = new Consumer($config);
while(true)
{
    $message = $consumer->consume();
    if($message)
    {
        var_dump($message->getKey() . ':' . $message->getValue());
        $consumer->ack($message->getPartition()); // 手动提交
    }
    sleep(1);
}`
切换了其他kafka版本一样报错

**Comment by Yurunsoft** [comment]
已修复，请先将版本更新为`dev-master`后，再尝试看下是否解决了你的问题

**Comment by a53abc** [comment]
使用了最新代码之后，触发了新的问题；
1、错误提示consumer group 异常，指定groupId后不再提示。
2、随便新指定了groupId后不能正常消费，报错如下
`
Fatal error: Uncaught longlang\phpkafka\Exception\KafkaErrorException: [1] The requested offset is not within the range of offsets maintained by the server. in /var/www
/html/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385
Stack trace:
#0 /var/www/html/vendor/longlang/phpkafka/src/Consumer/Consumer.php(181): longlang\phpkafka\Protocol\ErrorCode::check(1)
#1 /var/www/html/vendor/longlang/phpkafka/src/Consumer/Consumer.php(140): longlang\phpkafka\Consumer\Consumer->fetchMessages()
#2 /var/www/html/test/kafka/consumer.php(17): longlang\phpkafka\Consumer\Consumer->consume()
#3 {main}
  thrown in /var/www/html/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php on line 385
`
同时kafka端报错 信息如下
`[2020-11-22 10:01:41,040] INFO [GroupCoordinator 101]: Member -a05b97f6-9d72-43e0-b8ff-a7fe735a8ef1 in group test100 has failed, removing it from the
 group (kafka.coordinator.group.GroupCoordinator)`

使用已经存在的consumer group可以正常消费。

**Comment by Yurunsoft** [comment]
使用最新demo代码后问题解决

**Comment by leocavalcante** [comment]
I'm getting this one a lot because it is using a random client instead of the coordinator broker,this helps: https://github.com/longyan/phpkafka/pull/12 but it should be used in conjunction with https://github.com/longyan/phpkafka/pull/11

**Comment by Dawnry** [comment]
> 使用了最新代码之后，触发了新的问题；
> 1、错误提示consumer group 异常，指定groupId后不再提示。
> 2、随便新指定了groupId后不能正常消费，报错如下
> `Fatal error: Uncaught longlang\phpkafka\Exception\KafkaErrorException: [1] The requested offset is not within the range of offsets maintained by the server. in /var/www /html/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385 Stack trace: #0 /var/www/html/vendor/longlang/phpkafka/src/Consumer/Consumer.php(181): longlang\phpkafka\Protocol\ErrorCode::check(1) #1 /var/www/html/vendor/longlang/phpkafka/src/Consumer/Consumer.php(140): longlang\phpkafka\Consumer\Consumer->fetchMessages() #2 /var/www/html/test/kafka/consumer.php(17): longlang\phpkafka\Consumer\Consumer->consume() #3 {main} thrown in /var/www/html/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php on line 385`
> 同时kafka端报错 信息如下
> `[2020-11-22 10:01:41,040] INFO [GroupCoordinator 101]: Member -a05b97f6-9d72-43e0-b8ff-a7fe735a8ef1 in group test100 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)`
> 
> 使用已经存在的consumer group可以正常消费。


我也是提示The requested offset is not within the range of offsets maintained by the server。请问最后是怎么解决的，为什么随意指定groupId不能生效呢

**Comment by Yurunsoft** [comment]
> > 使用了最新代码之后，触发了新的问题；
> > 1、错误提示consumer group 异常，指定groupId后不再提示。
> > 2、随便新指定了groupId后不能正常消费，报错如下
> > `Fatal error: Uncaught longlang\phpkafka\Exception\KafkaErrorException: [1] The requested offset is not within the range of offsets maintained by the server. in /var/www /html/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385 Stack trace: #0 /var/www/html/vendor/longlang/phpkafka/src/Consumer/Consumer.php(181): longlang\phpkafka\Protocol\ErrorCode::check(1) #1 /var/www/html/vendor/longlang/phpkafka/src/Consumer/Consumer.php(140): longlang\phpkafka\Consumer\Consumer->fetchMessages() #2 /var/www/html/test/kafka/consumer.php(17): longlang\phpkafka\Consumer\Consumer->consume() #3 {main} thrown in /var/www/html/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php on line 385`
> > 同时kafka端报错 信息如下
> > `[2020-11-22 10:01:41,040] INFO [GroupCoordinator 101]: Member -a05b97f6-9d72-43e0-b8ff-a7fe735a8ef1 in group test100 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)`
> > 使用已经存在的consumer group可以正常消费。
> 
> 我也是提示The requested offset is not within the range of offsets maintained by the server。请问最后是怎么解决的，为什么随意指定groupId不能生效呢

如有问题，请开一个新的 issue，并提供可复现代码
