### ISSUE TITLE
请问什么原因导致了fetchMessages 中 $currentList 为空

### ISSUE THREAD

**Issue by suibianmzl** [longyan/phpkafka#26]
[ERROR] App\Exception\Handler\ErrorHandler: Invalid argument supplied for foreach()(2) in /Users/zhaoxingyan/data/hives-hyperf/vendor/longlang/phpkafka/src/Consumer/Consumer.php:293
Stack trace:
#0 /Users/zhaoxingyan/data/hives-hyperf/vendor/longlang/phpkafka/src/Consumer/Consumer.php(293): ErrorHandler(2, 'Invalid argumen...', '/Users/zhaoxing...', 293, Array)
#1 /Users/zhaoxingyan/data/hives-hyperf/vendor/longlang/phpkafka/src/Consumer/Consumer.php(225): longlang\phpkafka\Consumer\Consumer->fetchMessages()
#2 /Users/zhaoxingyan/data/hives-hyperf/vendor/longlang/phpkafka/src/Consumer/Consumer.php(203): longlang\phpkafka\Consumer\Consumer->consume()
#3 /Users/zhaoxingyan/data/hives-hyperf/vendor/hyperf/kafka/src/ConsumerManager.php(150): longlang\phpkafka\Consumer\Consumer->start()
#4 /Users/zhaoxingyan/data/hives-hyperf/vendor/hyperf/utils/src/Functions.php(80): class@anonymous->Hyperf\Kafka\{closure}()
#5 /Users/zhaoxingyan/data/hives-hyperf/vendor/hyperf/kafka/src/ConsumerManager.php(157): retry(0, Object(Closure), 10)
#6 /Users/zhaoxingyan/data/hives-hyperf/vendor/hyperf/process/src/AbstractProcess.php(134): class@anonymous->handle()

**Comment by Yurunsoft** [comment]
可能是获取MetaData没数据吧。是否可以提供可复现代码？

**Comment by suibianmzl** [comment]
配置信息
<img width="835" alt="配置" src="https://user-images.githubusercontent.com/6262877/111023210-b7a12080-8412-11eb-9cc9-2bb1dfeff2bb.png">

消费
![Uploading 消费.png…]()

**Comment by Yurunsoft** [comment]
已在 https://github.com/longyan/phpkafka/commit/69d35d62c849f0d2d5369fb4c0d6fcab082e23d5 增加防御性判断，但不确定这个问题是如何出现的。如果有条件，建议提供一下最小可复现代码并重新打开这个issue。

**Comment by suibianmzl** [comment]
好的，谢谢
