### ISSUE TITLE
For requests intended only for the leader

### ISSUE THREAD

**Issue by susueoe** [longyan/phpkafka#27]
PHP Fatal error:  Uncaught longlang\phpkafka\Exception\KafkaErrorException: [6] For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.

**Comment by Yurunsoft** [comment]
What's your longlang/phpkafka version?

If it is not the latest version, please update to the latest version first.

Please provide a reproducible code.
