### ISSUE TITLE
The requested offset is not within the range of offsets maintained by the server

### ISSUE THREAD

**Issue by Dawnry** [longyan/phpkafka#31]
php/7.2.33 ckafka/1.1.1 (https://cloud.tencent.com/document/product/597/11173)
longyan/phpkafka 1.1.2

使用examples里的代码运行，producer正常，consumer提示The requested offset is not within the range of offsets maintained by the server

![image](https://user-images.githubusercontent.com/26197306/111959221-2411d300-8b29-11eb-8bad-f792a4468213.png)

![image](https://user-images.githubusercontent.com/26197306/111959265-2ffd9500-8b29-11eb-83d3-9997447b483e.png)

![image](https://user-images.githubusercontent.com/26197306/111959479-7b17a800-8b29-11eb-9ff6-9b371c559e5f.png)

是因为groupId的问题吗

**Comment by Yurunsoft** [comment]
可以提供一下错误日志的调用堆栈吗

**Comment by Dawnry** [comment]
"file":"/data/www/lizard/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385",
"exception":"longlang\\phpkafka\\Exception\\KafkaErrorException","e_code":1,"e_msg":"[1] The requested offset is not within the range of offsets maintained by the server.",
"stack":["line: 0 /data/www/lizard/vendor/longlang/phpkafka/src/Consumer/Consumer.php(317): check()","line: 1 /data/www/lizard/vendor/longlang/phpkafka/src/Consumer/Consumer.php(225): fetchMessages()","line: 2 /data/www/lizard/app/Biz/V2/Commands/Kafka/ConsumerCommand.php(37): consume()","line: 3 unkown(0): handle()","line: 4 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()","line: 5 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\{closure}()","line: 6 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): callBoundMethod()","line: 7 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): call()","line: 8 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): call()","line: 9 /data/www/lizard/vendor/symfony/console/Command/Command.php(255): execute()","line: 10 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): run()","line: 11 /data/www/lizard/vendor/symfony/console/Application.php(982): run()","line: 12 /data/www/lizard/vendor/symfony/console/Application.php(255): doRunCommand()","line: 13 /data/www/lizard/vendor/symfony/console/Application.php(148): doRun()","line: 14 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): run()","line: 15 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): run()","line: 16 /data/www/lizard/artisan(40): handle()"]}


这样可以嘛

**Comment by Yurunsoft** [comment]
已经修复，尝试一下 `dev-master` 分支代码是否解决了你的问题

**Comment by Dawnry** [comment]
使用dev-master 提示另外一个报错

![image](https://user-images.githubusercontent.com/26197306/112247652-a4eadf00-8c8f-11eb-92ed-ccd492d4c265.png)


"file":"/data/www/lizard/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385",
"exception":"longlang\\phpkafka\\Exception\\KafkaErrorException",
"e_code":6,"e_msg":"[6] For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.",
"stack":["line: 0 /data/www/lizard/vendor/longlang/phpkafka/src/Consumer/Consumer.php(329): check()","line: 1 /data/www/lizard/vendor/longlang/phpkafka/src/Consumer/Consumer.php(227): fetchMessages()","line: 2 /data/www/lizard/app/Biz/V2/Commands/Kafka/ConsumerCommand.php(35): consume()","line: 3 unkown(0): handle()","line: 4 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()","line: 5 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\{closure}()","line: 6 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): callBoundMethod()","line: 7 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): call()","line: 8 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): call()","line: 9 /data/www/lizard/vendor/symfony/console/Command/Command.php(255): execute()","line: 10 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): run()","line: 11 /data/www/lizard/vendor/symfony/console/Application.php(982): run()","line: 12 /data/www/lizard/vendor/symfony/console/Application.php(255): doRunCommand()","line: 13 /data/www/lizard/vendor/symfony/console/Application.php(148): doRun()","line: 14 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): run()","line: 15 /data/www/lizard/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): run()","line: 16 /data/www/lizard/artisan(40): handle()"]} {"traceId":"20210324105213wR3b9lx34CeRJsf9ZO"}

**Comment by Yurunsoft** [comment]
增加了错误判断处理，部分错误码直接 `rejoin()`，更新下试试

**Comment by Dawnry** [comment]
報錯是沒了，但是消費不到數據是什麼原因呢...這個是不是對 騰訊提供的ckafka兼容性有點問題....

**Comment by Yurunsoft** [comment]
应该是在 rejoin，稍微等一下，如果还消费不到，是否方便留一个QQ或者微信，远程调试一下

**Comment by Dawnry** [comment]
我等了幾分鐘還是沒消費到，我的QQ：1025195746。咱們加個好友溝通吧

**Comment by Yurunsoft** [comment]
已修复：https://github.com/longyan/phpkafka/commit/d0c29745093cbd6bc3571247f3478ddc5d258fe6
