### ISSUE TITLE
组件中抛出异常 RuntimeException: Partition 0 doses not exists(0) 

### ISSUE THREAD

**Issue by suibianmzl** [longyan/phpkafka#33]
帮忙看下这个问题，谢谢大佬！
1. 抛出客户端异常 RuntimeException: Partition 0 doses not exists(0)  
<img width="1028" alt="客户端异常" src="https://user-images.githubusercontent.com/6262877/112988536-8ce6f400-9196-11eb-9d70-d1666148ac7d.png">

2.下面是kafka服务器的server.log中的信息
<img width="1331" alt="kafka服务端异常" src="https://user-images.githubusercontent.com/6262877/112988716-b869de80-9196-11eb-8ac9-9c89a1b3d3e4.png">

3.调用实例的代码
<img width="1032" alt="调用代码" src="https://user-images.githubusercontent.com/6262877/112992385-b570ed00-919a-11eb-85cd-500aa5c786ef.png">

4.配置信息
<img width="745" alt="配置代码" src="https://user-images.githubusercontent.com/6262877/112992537-d46f7f00-919a-11eb-9855-c47ffa4c2d51.png">

**Comment by Yurunsoft** [comment]
更新到最新的`dev-master`试一下

**Comment by suibianmzl** [comment]
已经更新dev-master 还是有这个问题 ，请帮忙定位下 ，谢谢了

**Comment by suibianmzl** [comment]
![image](https://user-images.githubusercontent.com/6262877/113426312-db4dfa00-9405-11eb-93bd-d90071863f27.png)
定位了下，$response 中的数据是,errorCode = 27 ,就会触发Partition xx doses not exists(0)
![image](https://user-images.githubusercontent.com/6262877/113426449-0f291f80-9406-11eb-91d9-44d4ee8bd56f.png)

**Comment by Yurunsoft** [comment]
kafka 问题一般和环境有关，我这边没法复现你的问题。

请提供一下最小可复现代码代码（建议是`longyan/phpkafka`原生写法，不要截图！）

如果提供代码后这边无法复现，需要配合远程调试或者提供可复现问题的调试环境

**Comment by imxuyou** [comment]
@Yurunsoft 
当kafka触发重平衡时，heartbeat协程会有概率比消费者协程先执行到\longlang\phpkafka\Consumer\Consumer::rejoin()方法，然后会生成一个新的\longlang\phpkafka\Consumer\OffsetManager对象绑定到Consumer对象。
这个时候OffsetManger对象的offsets属性是空的，在heartbeat协程的\longlang\phpkafka\Consumer\OffsetManager::updateOffsets()方法执行完成前，如果Consumer协程执行到了\longlang\phpkafka\Consumer\Consumer::fetchMessages()方法，就会因为`$this->getOffsetManager($topic)->getFetchOffset($partition)`访问了该属性抛出 partition not exists 的异常。

**Comment by allenyinx** [comment]
@Yurunsoft Could you please help provide a patch/fix for this issue? i didn't see any solution yet when you close the issue.
能否针对这个issue提供一个补丁？我们仔细看了这个issue里的comment，似乎并没有如何fix的solution.
多谢！

> kafka 问题一般和环境有关，我这边没法复现你的问题。
> 
> 请提供一下最小可复现代码代码（建议是`longyan/phpkafka`原生写法，不要截图！）
> 
> 如果提供代码后这边无法复现，需要配合远程调试或者提供可复现问题的调试环境
