### ISSUE TITLE
SwooleSocket报错

### ISSUE THREAD

**Issue by susueoe** [longyan/phpkafka#34]
Stack trace:
#0 vendor/longlang/phpkafka/src/Client/SwooleClient.php(130): longlang\phpkafka\Socket\SwooleSocket->recv()
#1 {main}
  thrown in vendor/longlang/phpkafka/src/Socket/SwooleSocket.php on line 132
[mutex.cc : 2338] RAW: Check w->waitp->cond == nullptr failed: Mutex::Fer while waiting on Condition
PHP Fatal error:  Uncaught longlang\phpkafka\Exception\SocketException: Could not recv data from stream,  [0] in vendor/longlang/phpkafka/src/Socket/SwooleSocket.php:132

* Kafka 环境是
* 
自建

> Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.4
Built => Mar 22 2021 11:44:09
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

```
# PHP 7.4.12 (cli) (built: Dec 30 2020 11:56:19) ( NTS DEBUG )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies


```

```

**Comment by Yurunsoft** [comment]
请按照模版提问，并提供可复现代码
