### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by susueoe** [longyan/phpkafka#35]
{"message":"longlang\\phpkafka\\Consumer\\Consumer::fetchMessages","context":[{"class":"RuntimeException","message":"Partition 11 doses not exists","code":0,"file":"vendor/longlang/phpkafka/src/Consumer/OffsetManager.php:142"}],"level":200,"level_name":"INFO","channel":"default","datetime":"2021-04-01T21:28:27.426031+08:00","extra":{"host":","traceid":"afeadb577ff94de3cc0c7af6f8196c24e858eaae"}}

PHP 7.4.12 (cli) (built: Dec 30 2020 11:56:19) ( NTS DEBUG )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by Yurunsoft** [comment]
请按照模版提问，并提供可复现代码
