### ISSUE TITLE
关于消费者使用建议

### ISSUE THREAD

**Issue by a53abc** [longyan/phpkafka#6]
当前在调用消费者对象时需要手动指定消费的partition 
`$config->setPartitions([0,1,2]);`
在有多个consumer进程时会有  [27] The group is rebalancing, so a rejoin is needed 异常。
期望可以改进consumer方法，不需要使用者人工指定partition， 如果是个多进程的消费方式就显得不太友好，特别是分布式部署时。
希望可以自动均衡分配consumer group对象的partition。

**Comment by Yurunsoft** [comment]
v1.1.0 版本新引入了分区分配策略，并且废弃了`partitions`参数。

具体可以查阅文档。
